// Redux actions related to people
export const CREATE_PERSON = 'CREATE_PERSON';
export const RETRIEVE_PEOPLE = 'RETRIEVE_PEOPLE';
export const RETRIEVE_PERSON = 'RETRIEVE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';


// Redux actions related to campaign actions
export const RETRIEVE_ACTIONS = 'RETRIEVE_ACTIONS';
export const RETRIEVE_ACTION = 'RETRIEVE_ACTION';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const CREATE_ACTION = 'CREATE_ACTION';
export const CLEAR_ACTION_HIGHLIGHTS = 'CLEAR_ACTION_HIGHLIGHTS';
export const HIGHLIGHT_ACTIONS = 'HIGHLIGHT_ACTIONS';
export const HIGHLIGHT_ACTION_ACTIVITY = 'HIGHLIGHT_ACTION_ACTIVITY';
export const HIGHLIGHT_ACTION_LOCATION = 'HIGHLIGHT_ACTION_LOCATION';
export const HIGHLIGHT_ACTION_ACTIVITY_PHASE = 'HIGHLIGHT_ACTION_ACTIVITY_PHASE';
export const HIGHLIGHT_ACTION_LOCATION_PHASE = 'HIGHLIGHT_ACTION_LOCATION_PHASE';
